name: Build Flycast libretro core for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Ensure submodules initialized
        run: git submodule update --init --recursive

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            git
          msystem: MINGW64

      - name: Build libretro core
        shell: msys2 {0}
        run: |
          mkdir -p build
          cd build
          cmake .. -G "MinGW Makefiles" -DLIBRETRO=ON -DCMAKE_BUILD_TYPE=Release
          mingw32-make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: flycast_libretro_windows_x64
          path: build/flycast_libretro.dll
